version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: America/New_York
    open-pull-requests-limit: 10
    reviewers:
      - acmetech
    labels:
      - dependencies
      - v5
    versioning-strategy: increase
