languageCode:           "en"
title:                  "TODC Bootstrap"
baseURL:                "https://todc.github.io/todc-bootstrap"
enableInlineShortcodes: true

pygmentsUseClasses:     true
# you can use ```lang if you want too
pygmentsCodeFences:     true

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "taxonomyTerm", "RSS"]

blackfriday:
  fractions:            false

publishDir:             "_gh_pages"
archetypeDir:           "site/archetypes"
assetDir:               "site/assets"
contentDir:             "site/content"
dataDir:                "site/data"
layoutDir:              "site/layouts"
staticDir:              "site/static"
themesDir:              "site/themes"

params:
  description:          "Google-styled theme for Bootstrap."
  authors:              "Tim O'Donnell, and the TODC Bootstrap contributors"
  social_image_path:    /docs/4.3/assets/brand/bootstrap-social.png
  social_logo_path:     /docs/4.3/assets/brand/bootstrap-social-logo.png

  current_version:      "4.3.1-4.3.1-alpha"
  current_ruby_version: "4.3.1-4.3.1-alpha"
  docs_version:         "4.3"
  repo:                 "https://github.com/todc/todc-bootstrap"
  twitter:              " "
  slack:                " "
  opencollective:       " "
  blog:                 " "
  expo:                 " "
  themes:               " "

  download:
    source:             "https://github.com/todc/todc-bootstrap/archive/v4.3.1-4.3.1-alpha.zip"
    dist:               "https://github.com/todc/todc-bootstrap/releases/download/v4.3.1-4.3.1-alpha/todc-bootstrap-4.3.1-4.3.1-alpha-dist.zip"

  cdn:
    # See https://www.srihash.org for info on how to generate the hashes
    css:              "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    css_hash:         "sha384-vvibzJJdbzjUAgANcLgozW4q5KNSwmWXJwjUDrDKcF40pRurqf/+yokJy6E9R0Bp"
    js:               "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    js_hash:          "sha384-u1WgC0J4DjCaowk/0fpsG/8pLnBBWiGCpk7+tg4LA6D3PpBpcpCvNXmWw5+qixAe"
    js_bundle:        "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
    js_bundle_hash:   "sha384-RFaZ3GjIVARx4amrbP1rGV9DmaP2zLUCLcYMeF5nD8r07hNHsGnj9PfHulpe+JBU"
    popper:           "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/umd/popper.min.js"
    popper_hash:      "sha384-L2pyEeut/H3mtgCBaUNw7KWzp5n9+4pDQiExs933/5QfaTh8YStYFFkOzSoXjlTb"

  bs:
    title:                  "Bootstrap"
    baseURL:                "https://getbootstrap.com"

    params:
      description:          "The most popular HTML, CSS, and JS library in the world."
      authors:              "Mark Otto, Jacob Thornton, and Bootstrap contributors"
      social_image_path:    /docs/4.3/assets/brand/todc-bootstrap-social.png
      social_logo_path:     /docs/4.3/assets/brand/todc-bootstrap-social-logo.png

      current_version:      "4.3.1"
      current_ruby_version: "4.3.1"
      docs_version:         "4.3"
      repo:                 "https://github.com/twbs/bootstrap"
      twitter:              "getbootstrap"
      slack:                "https://bootstrap-slack.herokuapp.com/"
      opencollective:       "https://opencollective.com/bootstrap"
      blog:                 "https://blog.getbootstrap.com/"
      expo:                 "https://expo.getbootstrap.com/"
      themes:               "https://themes.getbootstrap.com/"

      download:
        source:             "https://github.com/twbs/bootstrap/archive/v4.3.1.zip"
        dist:               "https://github.com/twbs/bootstrap/releases/download/v4.3.1/bootstrap-4.3.1-dist.zip"
