languageCode:           "en"
title:                  "TODC Bootstrap"
baseURL:                "https://todc.github.io/todc-bootstrap"
enableInlineShortcodes: true

# canonifyURLs:           true

pygmentsUseClasses:     true
# you can use ```lang if you want too
pygmentsCodeFences:     true

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "taxonomyTerm", "RSS"]

blackfriday:
  fractions:            false

publishDir:             "_gh_pages"

module:
  mounts:
    - source:           dist
      target:           static/docs/4.3/dist
    - source:           site/assets
      target:           assets
    - source:           site/content
      target:           content
    - source:           site/data
      target:           data
    - source:           site/layouts
      target:           layouts
    - source:           site/static
      target:           static
    - source:           site/static/docs/4.3/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           site/static/docs/4.3/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

params:
  description:          "Google-styled theme for Bootstrap."
  authors:              "Tim O'Donnell, and the TODC Bootstrap contributors"
  social_image_path:    /docs/4.3/assets/brand/bootstrap-social.png
  social_logo_path:     /docs/4.3/assets/brand/bootstrap-social-logo.png

  current_version:      "4.3.1-4.3.1-alpha"
  current_ruby_version: "4.3.1-4.3.1-alpha"
  rfs_version:          "9.0.2"
  docs_version:         "4.3"
  repo:                 "https://github.com/todc/todc-bootstrap"
  twitter:              " "
  slack:                " "
  opencollective:       " "
  blog:                 " "
  expo:                 " "
  themes:               " "
  icons:                "https://icons.getbootstrap.com/"

  download:
    source:             "https://github.com/todc/todc-bootstrap/archive/v4.3.1-4.3.1-alpha.zip"
    dist:               "https://github.com/todc/todc-bootstrap/releases/download/v4.3.1-4.3.1-alpha/todc-bootstrap-4.3.1-4.3.1-alpha-dist.zip"

  cdn:
    # See https://www.srihash.org for info on how to generate the hashes
    css:              "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    css_hash:         "sha384-eRsfMZuRwmaiTbRuwjVuRofg6J6u1NaJZBs6bhpA/8uWRU1PWwMc2fZhkdfNe5nV"
    js:               "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    js_hash:          "sha384-0UcHeLqNMYbeXIpGn487WCRzfpNwaFZAYZ9sp2svQhLfLJIa5+c9cbDJcMYjnL6K"
    js_bundle:        "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
    js_bundle_hash:   "sha384-aevUQ+4yWZ6ZlKI7YujmahyAWRCGUPEvW1/mgA+vXxy61jIvzTuk7VjcOqBuPJjn"
    popper:           "https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    popper_hash:      "sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"

  bs:
    title:                  "Bootstrap"
    baseURL:                "https://getbootstrap.com"

    params:
      description:          "The most popular HTML, CSS, and JS library in the world."
      authors:              "Mark Otto, Jacob Thornton, and Bootstrap contributors"
      social_image_path:    /docs/4.3/assets/brand/todc-bootstrap-social.png
      social_logo_path:     /docs/4.3/assets/brand/todc-bootstrap-social-logo.png

      current_version:      "4.3.1"
      current_ruby_version: "4.3.1"
      rfs_version:          "9.0.2"
      docs_version:         "4.3"
      repo:                 "https://github.com/twbs/bootstrap"
      twitter:              "getbootstrap"
      slack:                "https://bootstrap-slack.herokuapp.com/"
      opencollective:       "https://opencollective.com/bootstrap"
      blog:                 "https://blog.getbootstrap.com/"
      expo:                 "https://expo.getbootstrap.com/"
      themes:               "https://themes.getbootstrap.com/"

      download:
        source:             "https://github.com/twbs/bootstrap/archive/v4.3.1.zip"
        dist:               "https://github.com/twbs/bootstrap/releases/download/v4.3.1/bootstrap-4.3.1-dist.zip"
